title = "Notre-Dame de Paris"
baseURL = "https://828767.github.io"
languageCode = "zh-cn" # "en-us" default
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "zh"
SectionPagesMenu = "main"
Paginate = 9 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.zh]
    title = "Ananke"
    weight = 1
    contentDir = "content/zh"
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.en]
    title = "Ananke English"
    weight = 2
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-purple"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"
